filter {
  if [fields][log_type] == "fail2ban_log" {
    grok {
      patterns_dir => ["/etc/logstash/patterns"]
      match => [ "message", "%{FAIL2BAN_BAN}" ]
      add_tag => [ "ban" ]
      named_captures_only => true
    }

    mutate {
      remove_tag => ["_grokparsefailure"]
    }
  }
}
