filter {
  if [fields][log_type] == "vsftp_log" {
    grok {
      patterns_dir => ["/etc/logstash/patterns"]
      match => [ "message", "%{VSFTP_ATUH_FAIL}" ]
      # named_captures_only => true
    }

    mutate {
      remove_tag => ["_grokparsefailure"]
    }
  }
}
