output {
    if [fields][log_type] == "fail2ban_log" {
        #stdout {
        #      codec => rubydebug
        #}
        elasticsearch {
            hosts    => [ "https://192.168.1.1:9200" ]
            user     => "logstash_internal"
            password => "logstash_internal"
            ssl      => true
            cacert   => "/etc/logstash/http_ca.crt"
            index    => "filebeat-fail2ban-%{+YY-MM-dd}"
        }
    }
    if [fields][log_type] == "cmd_log" {
        #stdout {
        #      codec => rubydebug
        #}
        elasticsearch {
            hosts    => [ "https://192.168.1.1:9200" ]
            user     => "logstash_internal"
            password => "logstash_internal"
            ssl      => true
            cacert   => "/etc/logstash/http_ca.crt"
            index    => "filebeat-cmd-%{+YY-MM-dd}"
        }
    }
    if [fields][log_type] == "vsftp_log" {
        # stdout {
        #       codec => rubydebug
        # }
        elasticsearch {
            hosts    => [ "https://192.168.1.1:9200" ]
            user     => "logstash_internal"
            password => "logstash_internal"
            ssl      => true
            cacert   => "/etc/logstash/http_ca.crt"
            index    => "filebeat-vsftp-%{+YY-MM-dd}"
        }
    }
    if [fields][log_type] == "ssh_log" {
        elasticsearch {
            hosts    => [ "https://192.168.1.1:9200" ]
            user     => "logstash_internal"
            password => "logstash_internal"
            ssl      => true
            cacert   => "/etc/logstash/http_ca.crt"  
            index    => "filebeat-ssh-%{+YY-MM-dd}"
        }
    }
}
